# Generated by Django 3.0.5 on 2020-07-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='descriptions',
            field=models.CharField(max_length=300),
        ),
    ]
